---
title: "Isabelle Mosss"
output: 
  flexdashboard::flex_dashboard:
  storyboard: true
  orientation: columns
  vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(spotifyr)
library(compmus)


apricots_bicep <-
  get_tidy_audio_analysis("0WfOuXw05LJq4ik1lVvTzi") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)


river_bodzin <-
  get_tidy_audio_analysis("215z00CrTsmjBop1O4kbWz") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)


```

Introduction 
===
-----------------------------------------------------------------------

### Introduction

```{.tabset} 

I will be investigating the songs of the famous duo Bicep and compare this to the songs of Stephan Bodzin. Both Bicep and Bodzin are an electronic artists and have a very different but characteristic style. A fan can immediately recognize a Bicep / Stephan Bodzin song.

Bodzins songs typically have a baseline driven, emotive and hypnotic synth.

Biceps songs have an immediately recognisable shuffling beat, subtle bass and soaring vocals are a surefire way to get any rave absolutely heaving.

However these artists have a very different electornic style, I think these artists are one of my all time favourites and I will never bore me. Therefore I am wondering if there are any simmilarities between the artists to figure out what makes me love them.

My corpus consists of the 'This is Bicep' playlist on spotify and the 'This is Stephan Bodzin' playlist.

```
Global comparison of Bicep and Bodzin
===
Column {data-width=600}
---------------------------

### Global comparison of Bicep and Bodzin
```{r}



```




Chromograms 
===
Column {data-width=600}
---------------------------

### Visualisation

```{r}
apricots_bicep %>%
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c() + ggtitle('Apricots from Bicep')

river_bodzin %>%
  mutate(pitches = map(pitches, compmus_normalise, "euclidean")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c() + ggtitle("River from Bodzin")
```

Column {data-width=400}
-------------------------------------

```.tabset{}

here is some textttt

```




Cepstrograms
===
Column {data-width=300}
---------------------------
### Cepstrograms 
```{r}

ataraxia <-
  get_tidy_audio_analysis("6wIlFCtQHeC8UyljWYnMoI") %>% # Change URI.
  compmus_align(bars, segments) %>%                     # Change `bars`
  select(bars) %>%                                      #   in all three
  unnest(bars) %>%                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) %>%
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )

ataraxia %>%
  compmus_gather_timbre() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic() + ggtitle("Ataraxia - Stephan Bodzin")


singularity <-
  get_tidy_audio_analysis("0yuJtvXsapVOQfNDYxQ5mw") %>% # Change URI.
  compmus_align(bars, segments) %>%                     # Change `bars`
  select(bars) %>%                                      #   in all three
  unnest(bars) %>%                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) %>%
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )

singularity %>%
  compmus_gather_timbre() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic() + ggtitle("Singularity - Stephan Bodzin")



boavista <-
  get_tidy_audio_analysis("3hw5kx3JoJ5k5SUAJRlmFq") %>% # Change URI.
  compmus_align(bars, segments) %>%                     # Change `bars`
  select(bars) %>%                                      #   in all three
  unnest(bars) %>%                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) %>%
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )

boavista %>%
  compmus_gather_timbre() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic() + ggtitle("Boavista - Stephan Bodzin")



glue <-
  get_tidy_audio_analysis("2aJDlirz6v2a4HREki98cP") %>% # Change URI.
  compmus_align(bars, segments) %>%                     # Change `bars`
  select(bars) %>%                                      #   in all three
  unnest(bars) %>%                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) %>%
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )

glue %>%
  compmus_gather_timbre() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic() + ggtitle("Glue - Bicep")



atlas <-
  get_tidy_audio_analysis("54TgI46OnNqcf0SyzQyCL6") %>% # Change URI.
  compmus_align(bars, segments) %>%                     # Change `bars`
  select(bars) %>%                                      #   in all three
  unnest(bars) %>%                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) %>%
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )

atlas %>%
  compmus_gather_timbre() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic() + ggtitle("Atlas - Bicep")



apricots <-
  get_tidy_audio_analysis("0WfOuXw05LJq4ik1lVvTzi") %>% # Change URI.
  compmus_align(bars, segments) %>%                     # Change `bars`
  select(bars) %>%                                      #   in all three
  unnest(bars) %>%                                      #   of these lines.
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  ) %>%
  mutate(
    timbre =
      map(segments,
        compmus_summarise, timbre,
        method = "rms", norm = "euclidean"              # Change summary & norm.
      )
  )

apricots %>%
  compmus_gather_timbre() %>%
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = basis,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  scale_fill_viridis_c() +                              
  theme_classic() + ggtitle("Apricots - Bicep")

```

Column {data-width=400}
-------------------------------------

```.tabset{}

Some ceptrograms of both artists. 

```
Outlier
===
### Outliers of both artists. 

```{r}

glue <-
  get_tidy_audio_analysis("2aJDlirz6v2a4HREki98cP") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)

glue %>%
  mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c() + ggtitle('Glue - Bicep')



singularity <-
  get_tidy_audio_analysis("0yuJtvXsapVOQfNDYxQ5mw") %>%
  select(segments) %>%
  unnest(segments) %>%
  select(start, duration, pitches)

singularity %>%
  mutate(pitches = map(pitches, compmus_normalise, "chebyshev")) %>%
  compmus_gather_chroma() %>% 
  ggplot(
    aes(
      x = start + duration / 2,
      width = duration,
      y = pitch_class,
      fill = value
    )
  ) +
  geom_tile() +
  labs(x = "Time (s)", y = NULL, fill = "Magnitude") +
  theme_minimal() +
  scale_fill_viridis_c() + ggtitle("Singularity - Bodzin")


```
Column {data-width=400}
-------------------------------------

```.tabset{}


This is a visualisation of two outliers, one of both artists. I think of these songs as ‘outliers’ because they are by far the most popular songs of both artists so I thought it would be interesting to look if there are certain extraordinary properties or similarities within their chromagrams. 

First chromogram is from the song Glue by Bicep. The first part of the song is a repetition of the same rhythm, which is visible in the chromagram. The highest magnitude is around D and G#|Ab / G. After this it is visible that this same rhythm keeps repeating throughout the song, but as the song is building up more elements are added (a voice and other electronic sounds). This makes the chromagram very mixed and a bit messy. Even though it is still possible to see the repeating rhythm, which you will notice if you listen to Glue. 
An extraordinary part in the chromagram is the yellow (high magnitude) stripe in the middle of the chromagram. This represents the high-pitched vocals, which is characteristic of the song Glue. 

The second chromagram is of the most popular Stephan Bodzin song, namely ’Singularity’. It is clear from the chromagram that the throughout the whole song there is a high magnitude on the G#|Ab, A and B notes. This forms a yellow ‘band’ on the top of the chromagram, so this represents the repeating bass-synth rhythm which is only composed of two chords plus the typical Bodzin-style synthesizers (this will be very clear when you listen to the song). 
What makes this song so specials is that the built-up is actually very simple and keeps repeating; there are some high pitches throughout the songs but the basis is really these two chords.  

```
Keygrams 
===
### week 10.

```{r}

circshift <- function(v, n) {
  if (n == 0) v else c(tail(v, n), head(v, -n))
}

#      C     C#    D     Eb    E     F     F#    G     Ab    A     Bb    B
major_chord <-
  c(   1,    0,    0,    0,    1,    0,    0,    1,    0,    0,    0,    0)
minor_chord <-
  c(   1,    0,    0,    1,    0,    0,    0,    1,    0,    0,    0,    0)
seventh_chord <-
  c(   1,    0,    0,    0,    1,    0,    0,    1,    0,    0,    1,    0)

major_key <-
  c(6.35, 2.23, 3.48, 2.33, 4.38, 4.09, 2.52, 5.19, 2.39, 3.66, 2.29, 2.88)
minor_key <-
  c(6.33, 2.68, 3.52, 5.38, 2.60, 3.53, 2.54, 4.75, 3.98, 2.69, 3.34, 3.17)


key_templates <-
  tribble(
    ~name, ~template,
    "Gb:maj", circshift(major_key, 6),
    "Bb:min", circshift(minor_key, 10),
    "Db:maj", circshift(major_key, 1),
    "F:min", circshift(minor_key, 5),
    "Ab:maj", circshift(major_key, 8),
    "C:min", circshift(minor_key, 0),
    "Eb:maj", circshift(major_key, 3),
    "G:min", circshift(minor_key, 7),
    "Bb:maj", circshift(major_key, 10),
    "D:min", circshift(minor_key, 2),
    "F:maj", circshift(major_key, 5),
    "A:min", circshift(minor_key, 9),
    "C:maj", circshift(major_key, 0),
    "E:min", circshift(minor_key, 4),
    "G:maj", circshift(major_key, 7),
    "B:min", circshift(minor_key, 11),
    "D:maj", circshift(major_key, 2),
    "F#:min", circshift(minor_key, 6),
    "A:maj", circshift(major_key, 9),
    "C#:min", circshift(minor_key, 1),
    "E:maj", circshift(major_key, 4),
    "G#:min", circshift(minor_key, 8),
    "B:maj", circshift(major_key, 11),
    "D#:min", circshift(minor_key, 3)
  )


sundial <-
  get_tidy_audio_analysis("3gCurfVJRI2d5vov0eF6ka") %>%
  compmus_align(sections, segments) %>%
  select(sections) %>%
  unnest(sections) %>%
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "mean", norm = "manhattan"
      )
  )

sundial %>% 
  compmus_match_pitch_template(
    key_templates,         # Change to chord_templates if descired
    method = "euclidean",  # Try different distance metrics
    norm = "manhattan"     # Try different norms
  ) %>%
  ggplot(
    aes(x = start + duration / 2, width = duration, y = name, fill = d)
  ) +
  geom_tile() +
  theme_minimal() +
  labs(x = "Time (s)", y = "") + ggtitle("Sundial by Bicep, keygram") + scale_fill_viridis_c('energy')

sputnik <-
  get_tidy_audio_analysis("00BsCMMLOc0djHZWRm8Dlg") %>%
  compmus_align(sections, segments) %>%
  select(sections) %>%
  unnest(sections) %>%
  mutate(
    pitches =
      map(segments,
        compmus_summarise, pitches,
        method = "mean", norm = "manhattan"
      )
  )

sputnik %>% 
  compmus_match_pitch_template(
    key_templates,         # Change to chord_templates if descired
    method = "euclidean",  # Try different distance metrics
    norm = "manhattan"     # Try different norms
  ) %>%
  ggplot(
    aes(x = start + duration / 2, width = duration, y = name, fill = d)
  ) +
  geom_tile() +
  theme_minimal() +
  labs(x = "Time (s)", y = "") + ggtitle("Sputnik by Bodzin, keygram") + scale_fill_viridis_c('energy')



bicep <- get_playlist_audio_features("", "45igKB0TM7fCIDJVo8dWpZ")
bodzin <- get_playlist_audio_features("", "4DgGHEYzIbiKwBZaXdkVvF")
  
  
bicep %>%
  count(key_mode, sort = TRUE) %>%
  ggplot(aes(reorder(key_mode, n), n))+
  geom_col(fill = "#6495ED") + coord_flip() + labs() + ggtitle("histogram of keys - Bicep ")

bodzin %>%
  count(key_mode, sort = TRUE) %>%
  ggplot(aes(reorder(key_mode, n), n))+
  geom_col(fill = "#6495ED") + coord_flip() + labs() + ggtitle("histogram of keys - Bodzin")


```

-------------------------------------

```.tabset{}

dark = more energy // light = little energy. 

Above is a histogram of keys for both the Bicep and Bodzin playlists I Made for my corpus.

Clearly, the C minor and A minor are significantly prevailing in Biceps music.According to Pauer, C minor is the key that is expressive of softness, longing, sadness, solemnity, dignified earnestness, and a passionate intensity. It lends itself most effectively to the portraiture of the supernatural (source https://interlude.hk/feel-key-c-minor/#:~:text=According%20to%20Pauer%2C%20C%20minor,the%20portraiture%20of%20the%20supernatural).

The G major and A# minor are prevailing in Bodzins music. G major is expressing the Serious, Magnificent and fantasy (source https://ledgernote.com/blog/interesting/musical-key-characteristics-emotions/). If would say this is reflected in Bodzins' music: his songs sound extraterrestrial which I would say is mainly caused by his characteristic base sound. 
Also I plotted some keygrams from both Bicep and Bodzin to see whether these songs reflects the most typical keys of the artist. [further explanation]


```


Conclusion, discussion
===
### Conclusion and Discussion

```{r}

```

